import "@/app/styles/globals.css";
import DashboardNavbar from "@/components/DashboardNavbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <>
            <DashboardNavbar />
            {children}
        </>
    );
}
